services:
  web:
    build: .
    environment:
      - IS_DOCKER=True
    ports:
      - "8081:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: syncsheets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: